"""
DINOv2 Vehicle Sub-Classifier
==============================
Fast (~3-6ms/crop) vehicle type classification using frozen DINOv2-small
embeddings + trained linear probe.

Falls back to SigLIP/heuristics if probe weights not found.

Install: pip install transformers torch scikit-learn
Weights: weights/dino_vehicle_probe/ (generated by train_dino_probe.py)
"""

from __future__ import annotations

import json
import pickle
import sys
from pathlib import Path
from typing import Optional

import cv2
import numpy as np

sys.path.insert(0, str(Path(__file__).parent.parent))
import config as cfg

# ─── Constants ────────────────────────────────────────────────────────────────

DINO_MODEL_NAME = "facebook/dinov2-small"
DINO_EMBED_DIM = 384

# DINOv2 normalization (ImageNet)
DINO_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
DINO_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)

DEFAULT_WEIGHTS_DIR = "Code" / "weights" / "dino_vehicle_probe"


# ─── Classifier ───────────────────────────────────────────────────────────────

class DINOv2VehicleClassifier:
    """
    Fast vehicle sub-classifier using DINOv2-small + sklearn linear probe.

    Lazy-loads model on first call. Returns None if weights not found.
    """

    def __init__(self, weights_dir: str | Path = DEFAULT_WEIGHTS_DIR):
        self._weights_dir = Path(weights_dir)
        self._dino = None
        self._processor = None
        self._probe = None
        self._torch_probe = None
        self._class_names: list[str] | None = None
        self._device = None
        self._available: bool | None = None  # None=unchecked

    def _ensure_loaded(self) -> bool:
        """Load DINOv2 and probe weights. Returns True if ready."""
        if self._available is not None:
            return self._available

        try:
            import torch
            from transformers import AutoImageProcessor, AutoModel

            # Check weights exist
            sklearn_path = self._weights_dir / "dino_probe_sklearn.pkl"
            torch_path = self._weights_dir / "dino_probe_torch.pth"
            names_path = self._weights_dir / "dino_class_names.json"

            has_sklearn = sklearn_path.exists()
            has_torch = torch_path.exists()

            if not has_sklearn and not has_torch:
                print(f"[DINOv2Classifier] No probe weights in {self._weights_dir}")
                self._available = False
                return False

            if not names_path.exists():
                print(f"[DINOv2Classifier] Missing {names_path}")
                self._available = False
                return False

            # Load class names
            with open(names_path) as f:
                self._class_names = json.load(f)

            # Load DINOv2
            self._device = torch.device(
                "cuda" if torch.cuda.is_available() else "cpu")

            self._dino = AutoModel.from_pretrained(DINO_MODEL_NAME)
            self._dino = self._dino.to(self._device)
            self._dino.eval()
            for param in self._dino.parameters():
                param.requires_grad = False

            self._processor = AutoImageProcessor.from_pretrained(DINO_MODEL_NAME)

            # Load sklearn probe (preferred)
            if has_sklearn:
                with open(sklearn_path, "rb") as f:
                    self._probe = pickle.load(f)

            # Load torch probe as fallback
            if has_torch:
                import torch.nn as tnn
                num_classes = len(self._class_names)
                self._torch_probe = tnn.Linear(DINO_EMBED_DIM, num_classes)
                self._torch_probe.load_state_dict(
                    torch.load(torch_path, map_location="cpu", weights_only=True))
                self._torch_probe.eval()

            probe_type = "sklearn" if self._probe is not None else "torch"
            print(f"[DINOv2Classifier] Loaded. Device: {self._device}. "
                  f"Probe: {probe_type}. "
                  f"Classes: {self._class_names}")

            self._available = True
            return True

        except Exception as e:
            print(f"[DINOv2Classifier] Failed to load: {e}")
            self._available = False
            return False

    def _preprocess(self, crop_bgr: np.ndarray) -> np.ndarray:
        """
        Preprocess a BGR crop to a normalized float32 tensor (C, H, W).
        """
        # BGR -> RGB
        rgb = cv2.cvtColor(crop_bgr, cv2.COLOR_BGR2RGB)
        # Resize to 224x224
        rgb = cv2.resize(rgb, (224, 224), interpolation=cv2.INTER_LINEAR)
        # To float [0, 1]
        img = rgb.astype(np.float32) / 255.0
        # Normalize
        img = (img - DINO_MEAN) / DINO_STD
        # HWC -> CHW
        img = img.transpose(2, 0, 1)
        return img

    def _embed_batch(self, crops_bgr: list[np.ndarray]) -> np.ndarray:
        """
        Extract CLS embeddings for a batch of BGR crops.
        Returns numpy array of shape (N, 384).
        """
        import torch

        tensors = [self._preprocess(c) for c in crops_bgr]
        batch = torch.from_numpy(np.stack(tensors)).to(self._device)

        with torch.no_grad():
            outputs = self._dino(batch)
            cls_embeddings = outputs.last_hidden_state[:, 0, :]

        return cls_embeddings.cpu().numpy()

    def _predict(self, embeddings: np.ndarray) -> list[dict]:
        """
        Run probe on embeddings. Returns list of result dicts.
        Uses sklearn probe if available, else torch probe.
        """
        results = []

        if self._probe is not None:
            # sklearn path (preferred — calibrated probabilities)
            probs = self._probe.predict_proba(embeddings)
            preds = self._probe.predict(embeddings)

            for i in range(len(preds)):
                class_idx = preds[i]
                prob_vec = probs[i]
                max_prob = float(prob_vec.max())
                class_name = self._class_names[class_idx]

                all_probs = {
                    self._class_names[j]: round(float(prob_vec[j]), 4)
                    for j in range(len(self._class_names))
                }

                if max_prob > 0.5:
                    conf_label = "high"
                elif max_prob > 0.25:
                    conf_label = "medium"
                else:
                    conf_label = "low"

                results.append({
                    "subclass": class_name,
                    "confidence": round(max_prob, 4),
                    "confidence_label": conf_label,
                    "all_probs": all_probs,
                    "method": "dinov2_probe",
                })
        else:
            # torch fallback
            import torch

            emb_tensor = torch.from_numpy(embeddings).float()
            with torch.no_grad():
                logits = self._torch_probe(emb_tensor)
                probs = torch.softmax(logits, dim=1).numpy()

            for i in range(len(probs)):
                prob_vec = probs[i]
                class_idx = int(prob_vec.argmax())
                max_prob = float(prob_vec.max())
                class_name = self._class_names[class_idx]

                all_probs = {
                    self._class_names[j]: round(float(prob_vec[j]), 4)
                    for j in range(len(self._class_names))
                }

                if max_prob > 0.5:
                    conf_label = "high"
                elif max_prob > 0.25:
                    conf_label = "medium"
                else:
                    conf_label = "low"

                results.append({
                    "subclass": class_name,
                    "confidence": round(max_prob, 4),
                    "confidence_label": conf_label,
                    "all_probs": all_probs,
                    "method": "dinov2_probe_torch",
                })

        return results

    def classify_single(self, crop_bgr: np.ndarray) -> dict | None:
        """
        Classify a single BGR crop.

        Args:
            crop_bgr: BGR numpy array (any size)

        Returns:
            Result dict or None if not available.
        """
        if not self.is_available():
            return None

        try:
            embedding = self._embed_batch([crop_bgr])
            results = self._predict(embedding)
            return results[0] if results else None
        except Exception as e:
            print(f"[DINOv2Classifier] classify_single error: {e}")
            return None

    def classify_batch(self, crops_bgr: list[np.ndarray]) -> list[dict | None]:
        """
        Batch inference: process all crops in one DINOv2 forward pass.

        Args:
            crops_bgr: list of BGR numpy arrays (any size)

        Returns:
            List of result dicts (same format as classify_single).
        """
        if not self.is_available() or not crops_bgr:
            return [None] * len(crops_bgr)

        try:
            # Filter out None/empty crops
            valid_indices = []
            valid_crops = []
            for i, c in enumerate(crops_bgr):
                if c is not None and c.size > 0:
                    valid_indices.append(i)
                    valid_crops.append(c)

            if not valid_crops:
                return [None] * len(crops_bgr)

            embeddings = self._embed_batch(valid_crops)
            predictions = self._predict(embeddings)

            # Map back to original indices
            results: list[dict | None] = [None] * len(crops_bgr)
            for idx, pred in zip(valid_indices, predictions):
                results[idx] = pred
            return results

        except Exception as e:
            print(f"[DINOv2Classifier] classify_batch error: {e}")
            return [None] * len(crops_bgr)

    def is_available(self) -> bool:
        """Check if classifier is ready. Triggers lazy load on first call."""
        if self._available is None:
            self._ensure_loaded()
        return self._available


# ─── Singleton ────────────────────────────────────────────────────────────────

_classifier_instance: DINOv2VehicleClassifier | None = None


def get_classifier() -> DINOv2VehicleClassifier:
    """Get or create the singleton DINOv2 classifier."""
    global _classifier_instance
    if _classifier_instance is None:
        _classifier_instance = DINOv2VehicleClassifier()
    return _classifier_instance
